EXECUTABLE = cg1_ex4_mac
CC = g++
CPPFLAGS= -O3 -DMACOSX -Iglm-0.9.4.0 -I/usr/X11/include 
DEPS = glm-0.9.4.0/glm/glm.hpp glm-0.9.4.0/glm/gtc/constants.inl Context.hpp Texture.hpp Image.hpp GLSLShader.h
OBJ = cg1_ex4.o Context.o Texture.o Image.o GLSLShader.o
LIBS= -L/usr/X11/lib -lglut -framework OpenGL -lGLEW

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CPPFLAGS) $(INCLUDES)

$(EXECUTABLE): $(OBJ)
	$(CC) -o $@ $^ $(CPPFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f *.o *~ $(EXECUTABLE)