EXECUTABLE = cg1_ex2_mac
CC = g++
CPPFLAGS= -O3 -DMACOSX -Iglm-0.9.3.4
DEPS = glm-0.9.3.4/glm/glm.hpp cell.h context.h window.h projection.h objmodel.h
OBJ = cell.o context.o window.o projection.o cg1_ex2.o objmodel.o
LIBS= -framework GLUT -framework OpenGL

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

$(EXECUTABLE): $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f *.o *~ $(EXECUTABLE)